# Generated by Django 5.0.1 on 2024-02-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteProfileManager', '0023_websiteprofiledata_company_phone_number3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail_to',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_on', models.CharField(help_text='Enter Email on Which want to get user data and pdfs', max_length=150)),
            ],
        ),
    ]
