# Generated by Django 5.0.1 on 2024-02-13 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteProfileManager', '0024_mail_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail_to',
            options={'verbose_name_plural': 'Send Mail On'},
        ),
    ]
