# Generated by Django 5.0.1 on 2024-02-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteProfileManager', '0025_alter_mail_to_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail_to',
            options={'verbose_name': 'Mail', 'verbose_name_plural': 'Send Mail On'},
        ),
        migrations.AddField(
            model_name='websiteprofiledata',
            name='company_address2',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
