# Generated by Django 5.0.1 on 2024-03-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteProfileManager', '0026_alter_mail_to_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfig',
            name='smtp_backend',
            field=models.CharField(default='django.core.mail.backends.smtp.EmailBackend', editable=False, max_length=150),
        ),
    ]
